package com.greatlearning.coreexception;

public class ExceptionBasics {
	public static void main(String[] args) {

		try {
			int result = 10 / 0;
			System.out.println(result);
		} catch (NullPointerException | ArithmeticException | ArrayIndexOutOfBoundsException e) {
			// TODO: handle exception
			e.printStackTrace();

		}

		System.out.println("WELCOME TO GREAT LEARNING");
	}
}
